# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/8"

  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "vvv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = "true"
  end


  config.vm.provider "virtualbox" do |v|
	  v.memory = 2048
  end

  config.vm.define "www" do |www|
    www.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "www"
    www.vm.hostname = "www"
  end

end
