---
# tasks file for httpd

- name: Install EPEL Repo
  yum:
    name: epel-release
    state: present

- name: Install Nginx Server
  yum:
    name:  nginx
    state: present

- name: Configure softwre
  template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify:
    - Start Nginx

- name: Make Index page
  template:
    src: index.j2
    dest: /usr/share/nginx/html/index.html
    mode: 0777
