
MACHINES = {
  :server1 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.10.10', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vpnet"},
                ]
  },
  
  :server2 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.10.20', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vpnet"},
                ]
  },

  :client1 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.10.30', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vpnet"},
                ]
  },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provider "virtualbox" do |v|
         v.memory = 1024
         v.cpus = 2
        end

    end

  end

  config.vm.provision "ansible" do |ansible|
             ansible.playbook = "provisioning/playbook.yml"
             ansible.become = "true"
  end
end
