---
# tasks file for balancer

- name: Install and configure VRRP
  block:
    - name: Install keepkeepalived
      yum: name=keepalived state=present
    
    - name: Configure keepalived for routers
      template: src=keepalived.j2 dest=/etc/keepalived/keepalived.conf mode=0666 owner=root
    
    - name: Enable VRRP
      service:
        name: keepalived
        enabled: yes
        state: started
        
- name: Install Filebeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.2-x86_64.rpm
    state: present

- name: Copy filebeat config
  copy: src=filebeat.yml dest=/etc/filebeat/filebeat.yml

- block:
  - name: Enabe nginx config in filebeat
    command: mv /etc/filebeat/modules.d/nginx.yml.disabled /etc/filebeat/modules.d/nginx.yml
  ignore_errors: yes

- name: Install Nginx
  yum: name=nginx state=present

- name: Nginx config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf mode=0644

- name: Copy default config
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf

- name: Copy conifg file for CMS
  copy: src=cms.zzz.chat.conf dest=/etc/nginx/conf.d/cms.zzz.chat.conf

- name: Copy conifg file for Zabbix
  copy: src=zabbix.conf dest=/etc/nginx/conf.d/zabbix.conf

- name: Copy conifg file for Kibana
  copy: src=kibana.conf dest=/etc/nginx/conf.d/kibana.conf

- name: Extract crt
  unarchive:
    src: conf.tgz
    dest: /etc/nginx

- name: Enable Nginx
  service:
    name: nginx
    enabled: yes
    state: restarted

- name: Enable Filebeat
  service:
    name: filebeat
    enabled: yes
    state: started
    